emergency-food-pantry/Food-Pantry-Check-In

README.md

Ian contributor

---

database.sql

added database initialization

---

design.md

Planned out authorization, routes, data structures, and sample users.

getting organized and designing

---

package.json
src/tests/App.test.js

removed app test and updated test script

Location router tests

---

server/routes/order.router.js
server/tests/order.router.test.js

Should be 4 passing route tests for the order router - GET, POST, PUT, & DELETE.  Let me know if there should be any changes.

passing route tests

---

package.json

npm run test now runs with --watch and --detectOpenHandles options

updated test script

---

package.json

more fixing

---

database.sql
server/routes/order.router.js
server/tests/location.router.test.js
server/tests/order.router.test.js

Finish order router

---

src/components/App/App.js
src/components/CheckIn/CheckIn.js
src/components/Header/Header.js

- Luke got the menu functioning
- Bailey started the check-in component

Client mobile view

---

.gitignore
server/routes/order.router.js
server/strategies/user.strategy.js
server/tests/account.router.test.js
server/tests/location.router.test.js
server/tests/order.router.test.js

I did comment-out some tests because they don't have authorization setup yet, but I'll reenable them for the next pull request.

Authenticate The Order Router

---

src/components/CheckIn/CheckIn.js

other field in order entry form was not included in action.payload. fixed this so API calls work correctly.

fixed order placement bug

---

src/components/Dashboard/Dashboard.css
src/components/Dashboard/Dashboard.js

Realized I kept working on this branch instead of making a new one.  Oh well

more styling to the dashboard

---

src/components/Dashboard/Dashboard.js

dashboard refresh now stops once dashboard is no longer mounted. closes #123

Fix dashboard refresh

---

database.sql
server/routes/order.router.js
server/tests/order.router.test.js

#110 backend portion. added column to database and altered routes and tests to function properly with new column.

Add pickup name backend

---

src/components/CheckIn/CheckIn.css
src/components/CheckIn/CheckIn.js
src/components/Footer/Footer.css

Fixed footer issue, added title and instructions to client check-in views.  Closes #136

Checkin info

---

server/routes/location.router.js
src/components/CheckIn/CheckIn.js
src/components/Dashboard/Dashboard.js
src/components/Dashboard/ManualOrder.js
src/redux/reducers/index.js
src/redux/reducers/parkingLocations.js
src/redux/sagas/index.js
src/redux/sagas/locationsSaga.js

Close #140, close #147, and close #139.

Make parking spot a drop down

---

src/components/CheckIn/CheckIn.css
src/components/CheckIn/CheckIn.js
src/components/Dashboard/Dashboard.css
src/components/Dashboard/Dashboard.js
src/components/Dashboard/ManualOrder.js
src/components/Footer/Footer.css

Should close #132 , #141 , and #145

Dashboard fixes

---

server/routes/order.router.js

PUT /api/order/checkout/:id route now updates the account profile of the user show the correct latest order
closes 122

Update profile latest order 122

---

src/components/LoginPage/LoginPage.css
src/components/LoginPage/LoginPage.js
src/components/RegisterPage/RegisterPage.css
src/components/RegisterPage/RegisterPage.js

fixed error display

---

src/components/CheckIn/CheckIn.css
src/components/CheckIn/CheckIn.js

added back button to client checkin form

---

src/components/App/App.js
src/index.js

[EFP-3](https://codelation.atlassian.net/browse/EFP-3)

Added Intercom

---

package-lock.json
server/routes/order.router.js
src/components/Dashboard/Orders.js
src/redux/sagas/checkOutOrderSaga.js

[EFP-4](https://codelation.atlassian.net/browse/EFP-4)

Added Remove Button

---

server/routes/order.router.js
server/sql/sqlSelects.js
src/components/Dashboard/Dashboard.css
src/components/Dashboard/Orders.js
src/redux/sagas/checkOutOrderSaga.js
src/redux/sagas/completeOrdersSaga.js

[EFP-10](https://codelation.atlassian.net/browse/EFP-10)

Efp 10 date change

---

src/components/Dashboard/Orders.js

[EFP-10](https://codelation.atlassian.net/browse/EFP-10)

Changed Date Value

---

src/components/CheckIn/CheckIn.js
src/components/Dashboard/ManualOrder.js
src/components/Dashboard/Orders.js

[EFP-16](https://codelation.atlassian.net/browse/EFP-16)

Changed Verbiage

---

database.sql
package-lock.json
package.json
server/modules/encryption.js
server/routes/account.router.js
server/routes/order.router.js
src/components/App/App.js
src/components/CheckIn/CheckIn.js
src/components/Dashboard/Dashboard.css
src/components/Dashboard/ManualOrder.js
src/components/Dashboard/Orders.js
src/components/ForgotPage/ForgotPage.css
src/components/ForgotPage/ForgotPage.js
src/components/ForgotPage/ResetPage.js
src/components/LoginPage/LoginPage.js
src/index.js
src/redux/reducers/errorsReducer.js
src/redux/reducers/index.js
src/redux/reducers/loginReducer.js
src/redux/reducers/resetReducer.js
src/redux/sagas/checkOutOrderSaga.js
src/redux/sagas/completeOrdersSaga.js
src/redux/sagas/forgotPasswordSaga.js
src/redux/sagas/index.js
src/redux/sagas/loginSaga.js

This will be used to push all of the codelation code into the code base.

Codelation
